# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(600, 590)
        main_window.setMaximumWidth(600)
        main_window.setMaximumHeight(590)
        main_window.setMinimumWidth(600)
        main_window.setMinimumHeight(590)
        main_window.setStyleSheet("")
        main_window.setWindowIcon(QtGui.QIcon('assets/icon.png'))
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color: rgba(169,169,169, 0.95)\n"
"}\n"
"\n"
".QLabel{\n"
"    background: rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
".QLineEdit{\n"
"    background: rgba(105,105,105, 0.6);\n"
"    color: white;\n"
"}\n"
"\n"
".QListWidget {\n"
"    border: 4px inset rgba(0,0,0,0.65);\n"
"    color: black;\n"
"}\n"
"\n"
".QPushButton {\n"
"    border: none;\n"
"    color: white;\n"
"    background-color: #4a4a4a;\n"
"    border-radius: 4px;\n"
"    box-shadow: inset 0 0 0 0 #f9e506;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.typed_pick = QtWidgets.QLineEdit(self.centralwidget)
        self.typed_pick.setGeometry(QtCore.QRect(40, 130, 141, 21))
        self.typed_pick.setText("")
        self.typed_pick.setObjectName("typed_pick")
        self.typed_ban = QtWidgets.QLineEdit(self.centralwidget)
        self.typed_ban.setGeometry(QtCore.QRect(230, 130, 141, 21))
        self.typed_ban.setText("")
        self.typed_ban.setObjectName("typed_ban")
        self.typed_item = QtWidgets.QLineEdit(self.centralwidget)
        self.typed_item.setGeometry(QtCore.QRect(420, 130, 141, 21))
        self.typed_item.setText("")
        self.typed_item.setObjectName("typed_item")
        self.pick_list = QtWidgets.QListWidget(self.centralwidget)
        self.pick_list.setGeometry(QtCore.QRect(40, 160, 141, 141))
        self.pick_list.setObjectName("pick_list")
        self.ban_list = QtWidgets.QListWidget(self.centralwidget)
        self.ban_list.setGeometry(QtCore.QRect(230, 160, 141, 141))
        self.ban_list.setObjectName("ban_list")
        self.header_bans = QtWidgets.QLabel(self.centralwidget)
        self.header_bans.setGeometry(QtCore.QRect(230, 90, 141, 31))
        self.header_bans.setStyleSheet("")
        self.header_bans.setObjectName("header_bans")
        self.header_picks = QtWidgets.QLabel(self.centralwidget)
        self.header_picks.setGeometry(QtCore.QRect(40, 90, 141, 31))
        self.header_picks.setStyleSheet("")
        self.header_picks.setObjectName("header_picks")
        self.clear_picks = QtWidgets.QPushButton(self.centralwidget)
        self.clear_picks.setGeometry(QtCore.QRect(70, 330, 81, 23))
        self.clear_picks.setStyleSheet("#clear_picks:hover{\n"
"    color: lightgreen;\n"
"}")
        self.clear_picks.setObjectName("clear_picks")
        self.clear_bans = QtWidgets.QPushButton(self.centralwidget)
        self.clear_bans.setGeometry(QtCore.QRect(260, 330, 81, 23))
        self.clear_bans.setStyleSheet("#clear_bans:hover {\n"
"    color: pink;\n"
"}")
        self.clear_bans.setObjectName("clear_bans")
        self.clear_items = QtWidgets.QPushButton(self.centralwidget)
        self.clear_items.setGeometry(QtCore.QRect(450, 330, 81, 23))
        self.clear_items.setStyleSheet("#clear_items:hover {\n"
                                       "    color: lightblue;\n"
                                       "}")
        self.clear_items.setObjectName("clear_items")


#tu proba
        self.add_picks = QtWidgets.QPushButton(self.centralwidget)
        self.add_picks.setGeometry(QtCore.QRect(70, 305, 81, 23))
        self.add_picks.setStyleSheet("#add_picks:hover{\n"
                                       "    color: lightgreen;\n"
                                       "}")
        self.add_picks.setObjectName("add_picks")
        self.add_bans = QtWidgets.QPushButton(self.centralwidget)
        self.add_bans.setGeometry(QtCore.QRect(260, 305, 81, 23))
        self.add_bans.setStyleSheet("#add_bans:hover {\n"
                                      "    color: pink;\n"
                                      "}")
        self.add_bans.setObjectName("add_bans")
        self.add_items = QtWidgets.QPushButton(self.centralwidget)
        self.add_items.setGeometry(QtCore.QRect(450, 305, 81, 23))
        self.add_items.setStyleSheet("#add_items:hover {\n"
                                       "    color: lightblue;\n"
                                       "}")
        self.add_items.setObjectName("add_items")

# tu koniec proby
        self.status_viewer = QtWidgets.QLabel(self.centralwidget)
        self.status_viewer.setGeometry(QtCore.QRect(30, 390, 281, 131))
        self.status_viewer.setStyleSheet("")
        self.status_viewer.setObjectName("status_viewer")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(370, 430, 191, 71))
        self.start_button.setStyleSheet("#start_button:hover {\n"
"    color:red;\n"
"    border: 15px inset rgba(50, 50, 50, .65);\n"
"}")
        self.start_button.setObjectName("start_button")
        self.item_list = QtWidgets.QListWidget(self.centralwidget)
        self.item_list.setGeometry(QtCore.QRect(420, 160, 141, 141))
        self.item_list.setObjectName("item_list")
        self.header_items = QtWidgets.QLabel(self.centralwidget)
        self.header_items.setGeometry(QtCore.QRect(420, 90, 141, 31))
        self.header_items.setStyleSheet("")
        self.header_items.setObjectName("header_items")
        self.clear_items.setObjectName("clear_items")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-380, -10, 991, 701))
        self.label.setStyleSheet("background-image: url(katarina.jpg)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.typed_pick.raise_()
        self.typed_ban.raise_()
        self.typed_item.raise_()
        self.pick_list.raise_()
        self.ban_list.raise_()
        self.item_list.raise_()
        self.header_bans.raise_()
        self.header_picks.raise_()
        self.header_items.raise_()
        self.clear_picks.raise_()
        self.clear_bans.raise_()
        self.clear_items.raise_()
        self.add_picks.raise_()
        self.add_bans.raise_()
        self.add_items.raise_()
        self.status_viewer.raise_()
        self.start_button.raise_()
        main_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "LOL AUTO ACCEPT"))
        self.typed_pick.setToolTip(_translate("main_window", "<html><head/><body><p>co pickujesz?</p></body></html>"))
        self.typed_pick.setPlaceholderText(_translate("main_window", "what do you want to pick?"))
        self.typed_ban.setToolTip(_translate("main_window", "<html><head/><body><p>what do you pick?</p></body></html>"))
        self.typed_ban.setPlaceholderText(_translate("main_window", "what do you want to ban?"))
        self.header_bans.setText(_translate("main_window", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">BANS</span></p></body></html>"))
        self.header_picks.setText(_translate("main_window", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#45d000;\">PICKS</span></p></body></html>"))
        self.clear_picks.setText(_translate("main_window", "clear picks"))
        self.clear_bans.setText(_translate("main_window", "clear bans"))
        self.clear_items.setText(_translate("main_window", "clear items"))
        self.add_picks.setText(_translate("main_window", "add picks"))
        self.add_bans.setText(_translate("main_window", "add bans"))
        self.add_items.setText(_translate("main_window", "add items"))
        self.status_viewer.setText(_translate("main_window", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">PRESS START</span></p></body></html>"))
        self.start_button.setText(_translate("main_window", "START"))
        self.header_items.setText(_translate("main_window", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#0581c3;\">ITEMS</span></p></body></html>"))
        self.typed_item.setToolTip(_translate("main_window", "<html><head/><body><p>co pickujesz?</p></body></html>"))
        self.typed_item.setPlaceholderText(_translate("main_window", "what do you want to buy?"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())